<a href="https://colab.research.google.com/github/kghilothia06/intro-to-tensorflow/blob/master/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
a = tf.constant(10)

In [0]:
b=tf.constant(20)

In [4]:
print(a)

tf.Tensor(10, shape=(), dtype=int32)


In [0]:
c=tf.add(a,b)

In [7]:
print(c)

tf.Tensor(30, shape=(), dtype=int32)


In [0]:
string = tf.Variable("hello world!" , tf.string)


In [14]:
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello world!'>


In [0]:
string1 = tf.constant("hello")

In [12]:
print(string1)

tf.Tensor(b'hello', shape=(), dtype=string)


In [15]:
tf.rank(string1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [16]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [0]:
tensor1 = tf.Variable([["hi" ,"kush"] ,  ["nice","boy"]],tf.string)

In [19]:
print(tensor1)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'hi', b'kush'],
       [b'nice', b'boy']], dtype=object)>


In [20]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [34]:
with tf.compat.v1.Session() as sess:
  a = tf.constant(10)
  b = tf.constant(20)
  c = a+b
  print(sess.run(c))
  result = sess.run(c)

30


In [41]:
print(result)

b'helloworld'


In [40]:
with tf.compat.v1.Session() as sess:
  hello = tf.constant("hello")
  world = tf.constant("world")
  print(sess.run(hello + world))
  result = sess.run(hello + world)
  

b'helloworld'
